postgres:
  image: postgres
  volumes:
    # If you are using boot2docker, postgres data has to live in the VM for now until #581 is fixed
    # for more info see here: https://github.com/boot2docker/boot2docker/issues/581
    - /data/{{cookiecutter.repo_name}}/postgres:/var/lib/postgresql/data

django:
  build: .
  command: python /app/manage.py runserver_plus 0.0.0.0:8000
  volumes:
    - .:/app
    - /usr/local/lib
  ports:
    - "8000:8000"
  links:
    - postgres

debug:
  build: ./compose/debug/
  ports:
   - "8001:8000"
   - "2222:22"
  volumes_from:
   - django
  links:
   - postgres